// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dartz/dartz.dart' as _i5;
import 'package:flutter_app/core/network/secure_storage.dart' as _i4;
import 'package:flutter_app/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i3;
import 'package:flutter_app/features/auth/data/repositories/auth_repository_impl.dart'
    as _i11;
import 'package:flutter_app/features/auth/domain/entities/user_entity.dart'
    as _i2;
import 'package:flutter_app/features/music_player/data/datasources/music_local_data_source.dart'
    as _i7;
import 'package:flutter_app/features/music_player/data/datasources/music_remote_data_source.dart'
    as _i6;
import 'package:flutter_app/features/music_player/data/models/song_model.dart'
    as _i10;
import 'package:flutter_app/features/music_player/data/repositories/music_repository_impl.dart'
    as _i12;
import 'package:flutter_app/features/music_player/domain/entities/song_entity.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRemoteDataSource_1 extends _i1.SmartFake
    implements _i3.AuthRemoteDataSource {
  _FakeAuthRemoteDataSource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecureStorage_2 extends _i1.SmartFake implements _i4.SecureStorage {
  _FakeSecureStorage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i5.Either<L, R> {
  _FakeEither_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMusicRemoteDataSource_4 extends _i1.SmartFake
    implements _i6.MusicRemoteDataSource {
  _FakeMusicRemoteDataSource_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMusicLocalDataSource_5 extends _i1.SmartFake
    implements _i7.MusicLocalDataSource {
  _FakeMusicLocalDataSource_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i3.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i2.UserEntity> register(
    String? username,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [username, email, password]),
            returnValue: _i8.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#register, [username, email, password]),
              ),
            ),
          )
          as _i8.Future<_i2.UserEntity>);

  @override
  _i8.Future<_i2.UserEntity> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i8.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i8.Future<_i2.UserEntity>);
}

/// A class which mocks [MusicRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicRemoteDataSource extends _i1.Mock
    implements _i6.MusicRemoteDataSource {
  MockMusicRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i10.SongModel>> getOnlineSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getOnlineSongs, []),
            returnValue: _i8.Future<List<_i10.SongModel>>.value(
              <_i10.SongModel>[],
            ),
          )
          as _i8.Future<List<_i10.SongModel>>);
}

/// A class which mocks [MusicLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicLocalDataSource extends _i1.Mock
    implements _i7.MusicLocalDataSource {
  MockMusicLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i10.SongModel>> getLocalSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalSongs, []),
            returnValue: _i8.Future<List<_i10.SongModel>>.value(
              <_i10.SongModel>[],
            ),
          )
          as _i8.Future<List<_i10.SongModel>>);
}

/// A class which mocks [SecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i4.SecureStorage {
  MockSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [AuthRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepositoryImpl extends _i1.Mock
    implements _i11.AuthRepositoryImpl {
  MockAuthRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeAuthRemoteDataSource_1(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i3.AuthRemoteDataSource);

  @override
  _i4.SecureStorage get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeSecureStorage_2(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i4.SecureStorage);

  @override
  _i8.Future<_i5.Either<Exception, String>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i8.Future<_i5.Either<Exception, String>>.value(
              _FakeEither_3<Exception, String>(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i8.Future<_i5.Either<Exception, String>>);

  @override
  _i8.Future<_i5.Either<Exception, _i2.UserEntity>> register(
    String? username,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [username, email, password]),
            returnValue:
                _i8.Future<_i5.Either<Exception, _i2.UserEntity>>.value(
                  _FakeEither_3<Exception, _i2.UserEntity>(
                    this,
                    Invocation.method(#register, [username, email, password]),
                  ),
                ),
          )
          as _i8.Future<_i5.Either<Exception, _i2.UserEntity>>);

  @override
  _i8.Future<_i5.Either<Exception, _i2.UserEntity>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i8.Future<_i5.Either<Exception, _i2.UserEntity>>.value(
                  _FakeEither_3<Exception, _i2.UserEntity>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i8.Future<_i5.Either<Exception, _i2.UserEntity>>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [MusicRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicRepositoryImpl extends _i1.Mock
    implements _i12.MusicRepositoryImpl {
  MockMusicRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.MusicRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeMusicRemoteDataSource_4(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i6.MusicRemoteDataSource);

  @override
  _i7.MusicLocalDataSource get localDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#localDataSource),
            returnValue: _FakeMusicLocalDataSource_5(
              this,
              Invocation.getter(#localDataSource),
            ),
          )
          as _i7.MusicLocalDataSource);

  @override
  _i8.Future<_i5.Either<Exception, List<_i13.SongEntity>>> getOnlineSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getOnlineSongs, []),
            returnValue:
                _i8.Future<_i5.Either<Exception, List<_i13.SongEntity>>>.value(
                  _FakeEither_3<Exception, List<_i13.SongEntity>>(
                    this,
                    Invocation.method(#getOnlineSongs, []),
                  ),
                ),
          )
          as _i8.Future<_i5.Either<Exception, List<_i13.SongEntity>>>);

  @override
  _i8.Future<_i5.Either<Exception, List<_i13.SongEntity>>> getLocalSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalSongs, []),
            returnValue:
                _i8.Future<_i5.Either<Exception, List<_i13.SongEntity>>>.value(
                  _FakeEither_3<Exception, List<_i13.SongEntity>>(
                    this,
                    Invocation.method(#getLocalSongs, []),
                  ),
                ),
          )
          as _i8.Future<_i5.Either<Exception, List<_i13.SongEntity>>>);
}
