// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:dartz/dartz.dart' as _i5;
import 'package:dio/dio.dart' as _i13;
import 'package:flutter_app/core/network/secure_storage.dart' as _i8;
import 'package:flutter_app/features/admin/data/datasources/admin_remote_data_source.dart'
    as _i4;
import 'package:flutter_app/features/admin/data/repositories/admin_repository_impl.dart'
    as _i15;
import 'package:flutter_app/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i7;
import 'package:flutter_app/features/auth/data/repositories/auth_repository_impl.dart'
    as _i18;
import 'package:flutter_app/features/auth/domain/entities/user_entity.dart'
    as _i2;
import 'package:flutter_app/features/music_player/data/datasources/local_song_override_data_source.dart'
    as _i11;
import 'package:flutter_app/features/music_player/data/datasources/music_local_data_source.dart'
    as _i10;
import 'package:flutter_app/features/music_player/data/datasources/music_remote_data_source.dart'
    as _i9;
import 'package:flutter_app/features/music_player/data/models/local_song_override_model.dart'
    as _i17;
import 'package:flutter_app/features/music_player/data/models/song_model.dart'
    as _i6;
import 'package:flutter_app/features/music_player/data/repositories/music_repository_impl.dart'
    as _i19;
import 'package:flutter_app/features/music_player/domain/entities/local_song_override_entity.dart'
    as _i20;
import 'package:flutter_app/features/music_player/domain/entities/song_entity.dart'
    as _i3;
import 'package:flutter_app/features/reading_book/data/datasources/book_file_data_source.dart'
    as _i21;
import 'package:flutter_app/features/reading_book/data/datasources/book_library_data_source.dart'
    as _i23;
import 'package:flutter_app/features/reading_book/data/models/book_file_model.dart'
    as _i22;
import 'package:flutter_app/features/reading_book/data/models/book_model.dart'
    as _i12;
import 'package:flutter_app/features/reading_book/data/repositories/reading_book_repository_impl.dart'
    as _i24;
import 'package:flutter_app/features/reading_book/domain/entities/book_entity.dart'
    as _i26;
import 'package:flutter_app/features/reading_book/domain/entities/book_file_entity.dart'
    as _i25;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSongEntity_1 extends _i1.SmartFake implements _i3.SongEntity {
  _FakeSongEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminRemoteDataSource_2 extends _i1.SmartFake
    implements _i4.AdminRemoteDataSource {
  _FakeAdminRemoteDataSource_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i5.Either<L, R> {
  _FakeEither_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSongModel_4 extends _i1.SmartFake implements _i6.SongModel {
  _FakeSongModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRemoteDataSource_5 extends _i1.SmartFake
    implements _i7.AuthRemoteDataSource {
  _FakeAuthRemoteDataSource_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecureStorage_6 extends _i1.SmartFake implements _i8.SecureStorage {
  _FakeSecureStorage_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMusicRemoteDataSource_7 extends _i1.SmartFake
    implements _i9.MusicRemoteDataSource {
  _FakeMusicRemoteDataSource_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMusicLocalDataSource_8 extends _i1.SmartFake
    implements _i10.MusicLocalDataSource {
  _FakeMusicLocalDataSource_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalSongOverrideDataSource_9 extends _i1.SmartFake
    implements _i11.LocalSongOverrideDataSource {
  _FakeLocalSongOverrideDataSource_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBookModel_10 extends _i1.SmartFake implements _i12.BookModel {
  _FakeBookModel_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_11 extends _i1.SmartFake implements _i13.BaseOptions {
  _FakeBaseOptions_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_12 extends _i1.SmartFake implements _i13.Interceptors {
  _FakeInterceptors_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_13 extends _i1.SmartFake
    implements _i13.HttpClientAdapter {
  _FakeHttpClientAdapter_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_14 extends _i1.SmartFake implements _i13.Transformer {
  _FakeTransformer_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_15<T1> extends _i1.SmartFake implements _i13.Response<T1> {
  _FakeResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_16 extends _i1.SmartFake implements _i13.Dio {
  _FakeDio_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AdminRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminRemoteDataSource extends _i1.Mock
    implements _i4.AdminRemoteDataSource {
  MockAdminRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i2.UserEntity>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i14.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
          )
          as _i14.Future<List<_i2.UserEntity>>);

  @override
  _i14.Future<List<_i2.UserEntity>> getUnverifiedUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUnverifiedUsers, []),
            returnValue: _i14.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
          )
          as _i14.Future<List<_i2.UserEntity>>);

  @override
  _i14.Future<_i2.UserEntity> verifyUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#verifyUser, [userId]),
            returnValue: _i14.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#verifyUser, [userId])),
            ),
          )
          as _i14.Future<_i2.UserEntity>);

  @override
  _i14.Future<_i2.UserEntity> updateUser(
    int? userId, {
    String? username,
    String? email,
    String? role,
    bool? isVerified,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [userId],
              {
                #username: username,
                #email: email,
                #role: role,
                #isVerified: isVerified,
              },
            ),
            returnValue: _i14.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(
                  #updateUser,
                  [userId],
                  {
                    #username: username,
                    #email: email,
                    #role: role,
                    #isVerified: isVerified,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i2.UserEntity>);

  @override
  _i14.Future<List<_i3.SongEntity>> getAllSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSongs, []),
            returnValue: _i14.Future<List<_i3.SongEntity>>.value(
              <_i3.SongEntity>[],
            ),
          )
          as _i14.Future<List<_i3.SongEntity>>);

  @override
  _i14.Future<_i3.SongEntity> updateSong(
    int? songId, {
    String? title,
    String? artist,
    String? album,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSong,
              [songId],
              {#title: title, #artist: artist, #album: album},
            ),
            returnValue: _i14.Future<_i3.SongEntity>.value(
              _FakeSongEntity_1(
                this,
                Invocation.method(
                  #updateSong,
                  [songId],
                  {#title: title, #artist: artist, #album: album},
                ),
              ),
            ),
          )
          as _i14.Future<_i3.SongEntity>);

  @override
  _i14.Future<void> deleteSong(int? songId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSong, [songId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [AdminRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminRepositoryImpl extends _i1.Mock
    implements _i15.AdminRepositoryImpl {
  MockAdminRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AdminRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeAdminRemoteDataSource_2(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i4.AdminRemoteDataSource);

  @override
  _i14.Future<_i5.Either<Exception, List<_i2.UserEntity>>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue:
                _i14.Future<_i5.Either<Exception, List<_i2.UserEntity>>>.value(
                  _FakeEither_3<Exception, List<_i2.UserEntity>>(
                    this,
                    Invocation.method(#getAllUsers, []),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, List<_i2.UserEntity>>>);

  @override
  _i14.Future<_i5.Either<Exception, List<_i2.UserEntity>>>
  getUnverifiedUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUnverifiedUsers, []),
            returnValue:
                _i14.Future<_i5.Either<Exception, List<_i2.UserEntity>>>.value(
                  _FakeEither_3<Exception, List<_i2.UserEntity>>(
                    this,
                    Invocation.method(#getUnverifiedUsers, []),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, List<_i2.UserEntity>>>);

  @override
  _i14.Future<_i5.Either<Exception, _i2.UserEntity>> verifyUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#verifyUser, [userId]),
            returnValue:
                _i14.Future<_i5.Either<Exception, _i2.UserEntity>>.value(
                  _FakeEither_3<Exception, _i2.UserEntity>(
                    this,
                    Invocation.method(#verifyUser, [userId]),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, _i2.UserEntity>>);

  @override
  _i14.Future<_i5.Either<Exception, _i2.UserEntity>> updateUser(
    int? userId, {
    String? username,
    String? email,
    String? role,
    bool? isVerified,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [userId],
              {
                #username: username,
                #email: email,
                #role: role,
                #isVerified: isVerified,
              },
            ),
            returnValue:
                _i14.Future<_i5.Either<Exception, _i2.UserEntity>>.value(
                  _FakeEither_3<Exception, _i2.UserEntity>(
                    this,
                    Invocation.method(
                      #updateUser,
                      [userId],
                      {
                        #username: username,
                        #email: email,
                        #role: role,
                        #isVerified: isVerified,
                      },
                    ),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, _i2.UserEntity>>);

  @override
  _i14.Future<_i5.Either<Exception, List<_i3.SongEntity>>> getAllSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSongs, []),
            returnValue:
                _i14.Future<_i5.Either<Exception, List<_i3.SongEntity>>>.value(
                  _FakeEither_3<Exception, List<_i3.SongEntity>>(
                    this,
                    Invocation.method(#getAllSongs, []),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, List<_i3.SongEntity>>>);

  @override
  _i14.Future<_i5.Either<Exception, _i3.SongEntity>> updateSong(
    int? songId, {
    String? title,
    String? artist,
    String? album,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSong,
              [songId],
              {#title: title, #artist: artist, #album: album},
            ),
            returnValue:
                _i14.Future<_i5.Either<Exception, _i3.SongEntity>>.value(
                  _FakeEither_3<Exception, _i3.SongEntity>(
                    this,
                    Invocation.method(
                      #updateSong,
                      [songId],
                      {#title: title, #artist: artist, #album: album},
                    ),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, _i3.SongEntity>>);

  @override
  _i14.Future<_i5.Either<Exception, void>> deleteSong(int? songId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSong, [songId]),
            returnValue: _i14.Future<_i5.Either<Exception, void>>.value(
              _FakeEither_3<Exception, void>(
                this,
                Invocation.method(#deleteSong, [songId]),
              ),
            ),
          )
          as _i14.Future<_i5.Either<Exception, void>>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i7.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<String> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i14.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i14.Future<String>);

  @override
  _i14.Future<_i2.UserEntity> register(
    String? username,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [username, email, password]),
            returnValue: _i14.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#register, [username, email, password]),
              ),
            ),
          )
          as _i14.Future<_i2.UserEntity>);

  @override
  _i14.Future<_i2.UserEntity> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i14.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i14.Future<_i2.UserEntity>);

  @override
  _i14.Future<_i2.UserEntity> updateProfile(
    String? username, {
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [username], {#email: email}),
            returnValue: _i14.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#updateProfile, [username], {#email: email}),
              ),
            ),
          )
          as _i14.Future<_i2.UserEntity>);

  @override
  _i14.Future<_i2.UserEntity> uploadProfilePicture(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePicture, [filePath]),
            returnValue: _i14.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#uploadProfilePicture, [filePath]),
              ),
            ),
          )
          as _i14.Future<_i2.UserEntity>);

  @override
  _i14.Future<void> changePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [currentPassword, newPassword]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<String?> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i14.Future<String?>.value(),
          )
          as _i14.Future<String?>);

  @override
  _i14.Future<void> resetPassword(String? token, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [token, newPassword]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [MusicRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicRemoteDataSource extends _i1.Mock
    implements _i9.MusicRemoteDataSource {
  MockMusicRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i6.SongModel>> getOnlineSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getOnlineSongs, []),
            returnValue: _i14.Future<List<_i6.SongModel>>.value(
              <_i6.SongModel>[],
            ),
          )
          as _i14.Future<List<_i6.SongModel>>);

  @override
  _i14.Future<_i6.SongModel> uploadSong({
    required String? title,
    required String? artist,
    String? album,
    required String? filePath,
    String? coverImagePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadSong, [], {
              #title: title,
              #artist: artist,
              #album: album,
              #filePath: filePath,
              #coverImagePath: coverImagePath,
            }),
            returnValue: _i14.Future<_i6.SongModel>.value(
              _FakeSongModel_4(
                this,
                Invocation.method(#uploadSong, [], {
                  #title: title,
                  #artist: artist,
                  #album: album,
                  #filePath: filePath,
                  #coverImagePath: coverImagePath,
                }),
              ),
            ),
          )
          as _i14.Future<_i6.SongModel>);
}

/// A class which mocks [MusicLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicLocalDataSource extends _i1.Mock
    implements _i10.MusicLocalDataSource {
  MockMusicLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i6.SongModel>> getLocalSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalSongs, []),
            returnValue: _i14.Future<List<_i6.SongModel>>.value(
              <_i6.SongModel>[],
            ),
          )
          as _i14.Future<List<_i6.SongModel>>);
}

/// A class which mocks [LocalSongOverrideDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalSongOverrideDataSource extends _i1.Mock
    implements _i11.LocalSongOverrideDataSource {
  MockLocalSongOverrideDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i17.LocalSongOverrideModel>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i14.Future<List<_i17.LocalSongOverrideModel>>.value(
              <_i17.LocalSongOverrideModel>[],
            ),
          )
          as _i14.Future<List<_i17.LocalSongOverrideModel>>);

  @override
  _i14.Future<_i17.LocalSongOverrideModel?> getById(String? songId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [songId]),
            returnValue: _i14.Future<_i17.LocalSongOverrideModel?>.value(),
          )
          as _i14.Future<_i17.LocalSongOverrideModel?>);

  @override
  _i14.Future<void> upsert(
    String? songId, {
    String? title,
    String? artist,
    String? album,
    String? coverImagePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsert,
              [songId],
              {
                #title: title,
                #artist: artist,
                #album: album,
                #coverImagePath: coverImagePath,
              },
            ),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> setBackendSongId(String? songId, int? backendSongId) =>
      (super.noSuchMethod(
            Invocation.method(#setBackendSongId, [songId, backendSongId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [SecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i8.SecureStorage {
  MockSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i14.Future<String?>.value(),
          )
          as _i14.Future<String?>);

  @override
  _i14.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> saveUser(String? userJson) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [userJson]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<String?> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i14.Future<String?>.value(),
          )
          as _i14.Future<String?>);

  @override
  _i14.Future<void> deleteUser() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [AuthRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepositoryImpl extends _i1.Mock
    implements _i18.AuthRepositoryImpl {
  MockAuthRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.AuthRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeAuthRemoteDataSource_5(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i7.AuthRemoteDataSource);

  @override
  _i8.SecureStorage get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeSecureStorage_6(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i8.SecureStorage);

  @override
  _i14.Future<_i5.Either<Exception, String>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i14.Future<_i5.Either<Exception, String>>.value(
              _FakeEither_3<Exception, String>(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i14.Future<_i5.Either<Exception, String>>);

  @override
  _i14.Future<_i5.Either<Exception, _i2.UserEntity>> register(
    String? username,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [username, email, password]),
            returnValue:
                _i14.Future<_i5.Either<Exception, _i2.UserEntity>>.value(
                  _FakeEither_3<Exception, _i2.UserEntity>(
                    this,
                    Invocation.method(#register, [username, email, password]),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, _i2.UserEntity>>);

  @override
  _i14.Future<_i5.Either<Exception, _i2.UserEntity>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i14.Future<_i5.Either<Exception, _i2.UserEntity>>.value(
                  _FakeEither_3<Exception, _i2.UserEntity>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, _i2.UserEntity>>);

  @override
  _i14.Future<void> cacheUser(_i2.UserEntity? user) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUser, [user]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i2.UserEntity?> getCachedSession() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSession, []),
            returnValue: _i14.Future<_i2.UserEntity?>.value(),
          )
          as _i14.Future<_i2.UserEntity?>);

  @override
  _i14.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i5.Either<Exception, _i2.UserEntity>> updateProfile(
    String? username, {
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [username], {#email: email}),
            returnValue:
                _i14.Future<_i5.Either<Exception, _i2.UserEntity>>.value(
                  _FakeEither_3<Exception, _i2.UserEntity>(
                    this,
                    Invocation.method(
                      #updateProfile,
                      [username],
                      {#email: email},
                    ),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, _i2.UserEntity>>);

  @override
  _i14.Future<_i5.Either<Exception, _i2.UserEntity>> uploadProfilePicture(
    String? filePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePicture, [filePath]),
            returnValue:
                _i14.Future<_i5.Either<Exception, _i2.UserEntity>>.value(
                  _FakeEither_3<Exception, _i2.UserEntity>(
                    this,
                    Invocation.method(#uploadProfilePicture, [filePath]),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, _i2.UserEntity>>);

  @override
  _i14.Future<_i5.Either<Exception, void>> changePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [currentPassword, newPassword]),
            returnValue: _i14.Future<_i5.Either<Exception, void>>.value(
              _FakeEither_3<Exception, void>(
                this,
                Invocation.method(#changePassword, [
                  currentPassword,
                  newPassword,
                ]),
              ),
            ),
          )
          as _i14.Future<_i5.Either<Exception, void>>);

  @override
  _i14.Future<_i5.Either<Exception, String?>> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i14.Future<_i5.Either<Exception, String?>>.value(
              _FakeEither_3<Exception, String?>(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
          )
          as _i14.Future<_i5.Either<Exception, String?>>);

  @override
  _i14.Future<_i5.Either<Exception, void>> resetPassword(
    String? token,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [token, newPassword]),
            returnValue: _i14.Future<_i5.Either<Exception, void>>.value(
              _FakeEither_3<Exception, void>(
                this,
                Invocation.method(#resetPassword, [token, newPassword]),
              ),
            ),
          )
          as _i14.Future<_i5.Either<Exception, void>>);
}

/// A class which mocks [MusicRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicRepositoryImpl extends _i1.Mock
    implements _i19.MusicRepositoryImpl {
  MockMusicRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.MusicRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeMusicRemoteDataSource_7(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i9.MusicRemoteDataSource);

  @override
  _i10.MusicLocalDataSource get localDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#localDataSource),
            returnValue: _FakeMusicLocalDataSource_8(
              this,
              Invocation.getter(#localDataSource),
            ),
          )
          as _i10.MusicLocalDataSource);

  @override
  _i11.LocalSongOverrideDataSource get overrideDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#overrideDataSource),
            returnValue: _FakeLocalSongOverrideDataSource_9(
              this,
              Invocation.getter(#overrideDataSource),
            ),
          )
          as _i11.LocalSongOverrideDataSource);

  @override
  _i14.Future<_i5.Either<Exception, List<_i3.SongEntity>>> getOnlineSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getOnlineSongs, []),
            returnValue:
                _i14.Future<_i5.Either<Exception, List<_i3.SongEntity>>>.value(
                  _FakeEither_3<Exception, List<_i3.SongEntity>>(
                    this,
                    Invocation.method(#getOnlineSongs, []),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, List<_i3.SongEntity>>>);

  @override
  _i14.Future<_i5.Either<Exception, List<_i3.SongEntity>>> getLocalSongs() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalSongs, []),
            returnValue:
                _i14.Future<_i5.Either<Exception, List<_i3.SongEntity>>>.value(
                  _FakeEither_3<Exception, List<_i3.SongEntity>>(
                    this,
                    Invocation.method(#getLocalSongs, []),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, List<_i3.SongEntity>>>);

  @override
  _i14.Future<_i5.Either<Exception, void>> updateLocalSongMetadata(
    String? songId, {
    String? title,
    String? artist,
    String? album,
    String? coverImagePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateLocalSongMetadata,
              [songId],
              {
                #title: title,
                #artist: artist,
                #album: album,
                #coverImagePath: coverImagePath,
              },
            ),
            returnValue: _i14.Future<_i5.Either<Exception, void>>.value(
              _FakeEither_3<Exception, void>(
                this,
                Invocation.method(
                  #updateLocalSongMetadata,
                  [songId],
                  {
                    #title: title,
                    #artist: artist,
                    #album: album,
                    #coverImagePath: coverImagePath,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i5.Either<Exception, void>>);

  @override
  _i14.Future<_i5.Either<Exception, _i3.SongEntity>> uploadLocalSongToPublic(
    _i3.SongEntity? song, {
    String? coverImagePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadLocalSongToPublic,
              [song],
              {#coverImagePath: coverImagePath},
            ),
            returnValue:
                _i14.Future<_i5.Either<Exception, _i3.SongEntity>>.value(
                  _FakeEither_3<Exception, _i3.SongEntity>(
                    this,
                    Invocation.method(
                      #uploadLocalSongToPublic,
                      [song],
                      {#coverImagePath: coverImagePath},
                    ),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, _i3.SongEntity>>);

  @override
  _i14.Future<_i5.Either<Exception, List<_i20.LocalSongOverrideEntity>>>
  getLocalSongOverrides() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalSongOverrides, []),
            returnValue:
                _i14.Future<
                  _i5.Either<Exception, List<_i20.LocalSongOverrideEntity>>
                >.value(
                  _FakeEither_3<Exception, List<_i20.LocalSongOverrideEntity>>(
                    this,
                    Invocation.method(#getLocalSongOverrides, []),
                  ),
                ),
          )
          as _i14.Future<
            _i5.Either<Exception, List<_i20.LocalSongOverrideEntity>>
          >);
}

/// A class which mocks [BookFileDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookFileDataSource extends _i1.Mock
    implements _i21.BookFileDataSource {
  MockBookFileDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i22.BookFileModel>> scanPdfs() =>
      (super.noSuchMethod(
            Invocation.method(#scanPdfs, []),
            returnValue: _i14.Future<List<_i22.BookFileModel>>.value(
              <_i22.BookFileModel>[],
            ),
          )
          as _i14.Future<List<_i22.BookFileModel>>);
}

/// A class which mocks [BookLibraryDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookLibraryDataSource extends _i1.Mock
    implements _i23.BookLibraryDataSource {
  MockBookLibraryDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<List<_i12.BookModel>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i14.Future<List<_i12.BookModel>>.value(
              <_i12.BookModel>[],
            ),
          )
          as _i14.Future<List<_i12.BookModel>>);

  @override
  _i14.Future<_i12.BookModel> add({
    required String? filePath,
    required String? title,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#add, [], {#filePath: filePath, #title: title}),
            returnValue: _i14.Future<_i12.BookModel>.value(
              _FakeBookModel_10(
                this,
                Invocation.method(#add, [], {
                  #filePath: filePath,
                  #title: title,
                }),
              ),
            ),
          )
          as _i14.Future<_i12.BookModel>);

  @override
  _i14.Future<void> remove(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [id]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> setFavorite(int? id, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#setFavorite, [id, isFavorite]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> setLastPage(int? id, int? lastPage) =>
      (super.noSuchMethod(
            Invocation.method(#setLastPage, [id, lastPage]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [ReadingBookRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadingBookRepositoryImpl extends _i1.Mock
    implements _i24.ReadingBookRepositoryImpl {
  MockReadingBookRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i5.Either<Exception, List<_i25.BookFileEntity>>>
  scanDevicePdfs() =>
      (super.noSuchMethod(
            Invocation.method(#scanDevicePdfs, []),
            returnValue:
                _i14.Future<
                  _i5.Either<Exception, List<_i25.BookFileEntity>>
                >.value(
                  _FakeEither_3<Exception, List<_i25.BookFileEntity>>(
                    this,
                    Invocation.method(#scanDevicePdfs, []),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, List<_i25.BookFileEntity>>>);

  @override
  _i14.Future<_i5.Either<Exception, List<_i26.BookEntity>>> getGallery() =>
      (super.noSuchMethod(
            Invocation.method(#getGallery, []),
            returnValue:
                _i14.Future<_i5.Either<Exception, List<_i26.BookEntity>>>.value(
                  _FakeEither_3<Exception, List<_i26.BookEntity>>(
                    this,
                    Invocation.method(#getGallery, []),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, List<_i26.BookEntity>>>);

  @override
  _i14.Future<_i5.Either<Exception, _i26.BookEntity>> addToGallery(
    _i25.BookFileEntity? file,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addToGallery, [file]),
            returnValue:
                _i14.Future<_i5.Either<Exception, _i26.BookEntity>>.value(
                  _FakeEither_3<Exception, _i26.BookEntity>(
                    this,
                    Invocation.method(#addToGallery, [file]),
                  ),
                ),
          )
          as _i14.Future<_i5.Either<Exception, _i26.BookEntity>>);

  @override
  _i14.Future<_i5.Either<Exception, _i5.Unit>> removeFromGallery(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromGallery, [id]),
            returnValue: _i14.Future<_i5.Either<Exception, _i5.Unit>>.value(
              _FakeEither_3<Exception, _i5.Unit>(
                this,
                Invocation.method(#removeFromGallery, [id]),
              ),
            ),
          )
          as _i14.Future<_i5.Either<Exception, _i5.Unit>>);

  @override
  _i14.Future<_i5.Either<Exception, _i5.Unit>> toggleFavorite(
    int? id,
    bool? isFavorite,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id, isFavorite]),
            returnValue: _i14.Future<_i5.Either<Exception, _i5.Unit>>.value(
              _FakeEither_3<Exception, _i5.Unit>(
                this,
                Invocation.method(#toggleFavorite, [id, isFavorite]),
              ),
            ),
          )
          as _i14.Future<_i5.Either<Exception, _i5.Unit>>);

  @override
  _i14.Future<_i5.Either<Exception, _i5.Unit>> updateProgress(
    int? id,
    int? lastPage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgress, [id, lastPage]),
            returnValue: _i14.Future<_i5.Either<Exception, _i5.Unit>>.value(
              _FakeEither_3<Exception, _i5.Unit>(
                this,
                Invocation.method(#updateProgress, [id, lastPage]),
              ),
            ),
          )
          as _i14.Future<_i5.Either<Exception, _i5.Unit>>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i13.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_11(this, Invocation.getter(#options)),
          )
          as _i13.BaseOptions);

  @override
  _i13.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_12(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i13.Interceptors);

  @override
  _i13.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_13(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i13.HttpClientAdapter);

  @override
  _i13.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_14(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i13.Transformer);

  @override
  set options(_i13.BaseOptions? value) => super.noSuchMethod(
    Invocation.setter(#options, value),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i13.HttpClientAdapter? value) => super.noSuchMethod(
    Invocation.setter(#httpClientAdapter, value),
    returnValueForMissingStub: null,
  );

  @override
  set transformer(_i13.Transformer? value) => super.noSuchMethod(
    Invocation.setter(#transformer, value),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<_i13.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
    _i13.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
    _i13.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
    _i13.ProgressCallback? onSendProgress,
    _i13.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
    _i13.ProgressCallback? onSendProgress,
    _i13.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
    _i13.ProgressCallback? onSendProgress,
    _i13.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
    _i13.ProgressCallback? onSendProgress,
    _i13.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
    _i13.ProgressCallback? onSendProgress,
    _i13.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
    _i13.ProgressCallback? onSendProgress,
    _i13.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i13.Options? options,
    _i13.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i13.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i13.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i13.FileAccessMode? fileAccessMode = _i13.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i13.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i14.Future<_i13.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<dynamic>>);

  @override
  _i14.Future<_i13.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i13.ProgressCallback? onReceiveProgress,
    _i13.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i13.FileAccessMode? fileAccessMode = _i13.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i13.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i14.Future<_i13.Response<dynamic>>.value(
              _FakeResponse_15<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<dynamic>>);

  @override
  _i14.Future<_i13.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i13.CancelToken? cancelToken,
    _i13.Options? options,
    _i13.ProgressCallback? onSendProgress,
    _i13.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i13.CancelToken? cancelToken,
    _i13.Options? options,
    _i13.ProgressCallback? onSendProgress,
    _i13.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i14.Future<_i13.Response<T>> fetch<T>(_i13.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i14.Future<_i13.Response<T>>.value(
              _FakeResponse_15<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i14.Future<_i13.Response<T>>);

  @override
  _i13.Dio clone({
    _i13.BaseOptions? options,
    _i13.Interceptors? interceptors,
    _i13.HttpClientAdapter? httpClientAdapter,
    _i13.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_16(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i13.Dio);
}
